name: Generate Snake

on:
  schedule: # Chạy vào 12am UTC hàng ngày
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: TTHTech # Thay đổi với tên người dùng GitHub của bạn
          outputs: dist/snake.svg

      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
